@Northwind.WebApi_HostAddress = https://localhost:5001

GET {{Northwind.WebApi_HostAddress}}/api/customers/
Accept: application/json

###

GET {{Northwind.WebApi_HostAddress}}/api/customers/?country=Germany
Accept: application/json
